# Generated by Django 4.2.6 on 2023-10-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifierModel', '0003_modelfile_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelFile',
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
